env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - error
    - allow:
      - log
globals:
  application: true
  autoload: true
  app: true
  stagi: true
  actions: true
  describe: true
  expect: true
  it: true
